apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  ports:
    - port: 3003
      targetPort: 3003
      name: 'tcp'
      protocol: TCP
  selector:
    app: payments
  type: ClusterIP