apiVersion: v1
kind: Service
metadata:
  name: auth-http
  labels:
    app: auth
spec:
  ports:
    - port: 3001
      name: 'http'
      protocol: TCP
      targetPort: 3001
  selector:
    app: auth
  type: NodePort