version: '3.9'
services:
  e2e:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../data:/data/db
  
  reservations:
    image: tuantoquq/reservations:latest
    restart: always
    env_file:
      - ../apps/reservations/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  
  auth:
    image: tuantoquq/auth:latest
    restart: always
    env_file:
      - ../apps/auth/.env
    ports:
      - 3001:3001
    depends_on:
      - mongo
  
  payments:
    image: tuantoquq/payments:latest
    restart: always
    env_file:
      - ../apps/payments/.env
    ports:
      - 3003:3003
  
  notifications:
    image: tuantoquq/notifications:latest
    restart: always
    env_file:
      - ../apps/notifications/.env
    ports:
      - 3004:3004