apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservations
  template:
    metadata:
      labels:
        app: reservations
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/reservations-400309/reservations/production:latest
          name: reservations
          env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: HTTP_PORT
            value: "3000"
          - name: AUTH_SERVICE_HOST
            value: auth-tcp
          - name: AUTH_SERVICE_PORT
            value: "3002"
          - name: PAYMENTS_SERVICE_HOST
            value: payments
          - name: PAYMENTS_SERVICE_PORT
            value: "3003"
          ports:
            - containerPort: 3000
