apiVersion: v1
kind: Service
metadata:
  name: reservations
  labels:
    app: reservations
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: 'http'
      protocol: TCP
  selector:
    app: reservations
  type: NodePort