apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/reservations-400309/notifications/production:latest
          name: notifications
          env:
            - name: PORT
              value: "3004"
            - name: EMAIL_USERNAME
              value: "anhtuana22000@gmail.com"
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: emails
                  key: appPassword
          ports:
            - containerPort: 3004
