apiVersion: v1
kind: Service
metadata:
  name: notifications
  labels:
    app: notifications
spec:
  ports:
    - name: 'tcp'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: notifications
  type: ClusterIP